import { test, expect } from '@playwright/test'

/**
 * Direct-mode voting flow.
 *
 * Preconditions for this test to run meaningfully:
 *   1. A Hardhat node is running on :8545 with deployed contracts.
 *   2. At least one poll exists in the registry (so the dashboard has a card
 *      to click into).
 *
 * If no poll card is present on the home page, we treat that as a skip
 * signal — creating a poll from inside an E2E test is brittle and out of
 * scope for this suite. The poll creation flow has its own coverage path
 * (manual demo + future T-C work).
 *
 * Relayer-mode coverage is deferred: the Direct/Relayer toggle (T-C) is
 * not on dev/lvh at the time this suite was written. When T-C lands, add
 * a sibling describe block that flips the toggle to Relayer and asserts
 * the same end state.
 */
test.describe('Direct vote flow', () => {
    test('connects wallet, navigates to a poll, asserts the voting panel renders', async ({ page }) => {
        await page.goto('/')

        // Connect first — most poll UI is gated on connection state.
        await page.getByRole('button', { name: /Test Account/i }).click()
        await page.getByText(/0xf39F\.\.\.2266/i).waitFor({ state: 'visible' })

        // Detect whether a poll card exists. The Home page renders either
        // an empty-state "No polls yet" block OR a grid of poll cards
        // (each card is a Link to /poll/<address>).
        const emptyState = page.getByRole('heading', { name: /No polls yet/i })
        const pollLinks = page.locator('a[href^="/poll/"]')

        // Wait briefly for either branch to settle.
        await Promise.race([
            emptyState.waitFor({ state: 'visible', timeout: 5_000 }).catch(() => {}),
            pollLinks.first().waitFor({ state: 'visible', timeout: 5_000 }).catch(() => {}),
        ])

        const pollCount = await pollLinks.count()
        test.skip(
            pollCount === 0,
            'No poll deployed in registry — skip Direct-mode flow. Run `npm run deploy:local` in contracts/ and create at least one poll first.',
        )

        // Navigate to the first poll on the dashboard.
        await pollLinks.first().click()

        // Either Poll (anon) or BlindPoll page renders. Both expose an
        // "Identity" section as the per-poll voter-side entry point.
        const identityHeading = page.getByRole('heading', { name: /^Identity$/i })
        await identityHeading.waitFor({ state: 'visible' })
        await expect(identityHeading).toBeVisible()

        // The identity card exposes either a "Load Identity" button (for
        // anon polls, requires invite token) OR commit controls (blind).
        // Asserting that *some* voter-side control is reachable is enough
        // to prove the page rendered correctly for a connected wallet.
        const voterControl = page.locator('button', { hasText: /Load Identity|Commit|Reveal/i }).first()
        await expect(voterControl).toBeVisible()
    })

    test.skip('cast a Direct-mode vote end-to-end', async () => {
        // Deferred. Requires:
        //   - A deterministic poll deployed with known options.
        //   - An invite token generated by the poll admin (registerVoters).
        //   - Time-warp on the Hardhat node to advance into the voting phase.
        // These are not in scope for a self-contained dev-server-only suite.
        // Unblock when T-B/T-C land with a relayer + scriptable poll
        // bootstrap. See INSTRUCTIONS.md for the manual flow.
    })

    test.skip('cast a Relayer-mode vote end-to-end (unblock when T-C lands)', async () => {
        // The Direct/Relayer toggle is not present on dev/lvh as of this
        // commit. Re-enable this test once the frontend exposes the toggle
        // and the relayer service (T-B) is reachable from CI.
    })
})
